version: '3.5'
services:
  db:
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_DB=control_employee
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=127238
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d control_employee -U master"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  web:
    restart: on-failure
    build: .
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    command: sh -c "python manage.py migrate"
    depends_on:
      - db
  bot:
    restart: always
    build: .
    command: python manage.py runscript bot
    depends_on:
      - db
volumes:
  db_data:
  static_volume:
  media_volume:
