# Generated by Django 5.1.2 on 2024-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'Сотрудник'), (3, 'Руководитель'), (4, 'Директор'), (5, 'Новый сотрудник')], default=5),
        ),
    ]
