# Generated by Django 5.1.2 on 2024-10-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.department'),
        ),
    ]
