# Generated by Django 5.1.2 on 2024-10-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='begin',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего времени'),
        ),
        migrations.AlterField(
            model_name='department',
            name='begin_lanch',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало обеда'),
        ),
        migrations.AlterField(
            model_name='department',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец дня'),
        ),
        migrations.AlterField(
            model_name='department',
            name='end_lanch',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец обеда'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'Сотрудник'), (3, 'Руководитель'), (4, 'Директор'), (5, 'Новый сотрудник'), (6, 'Отказано в регистрации')], default=5),
        ),
    ]
