# Generated by Django 5.1.2 on 2024-10-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_tguser_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
    ]
